services:
  # We are forced to have a docker compose even for a single service since az cli commands expect
  # to find the CCF provider container as part of a compose project and look for a 'client-1'
  # container within.
  client:
    image: ${AZCLI_CCF_PROVIDER_CLIENT_IMAGE}
    ports:
      - "0:8080"
    environment:
      - IDENTITY_ENDPOINT=${CREDENTIAL_PROXY_ENDPOINT}
      - IMDS_ENDPOINT="dummy_required_value"
      - CCF_PROVIDER_RUN_JS_APP_VIRTUAL_IMAGE=${AZCLI_CCF_PROVIDER_RUN_JS_APP_VIRTUAL_IMAGE}
      - CCF_PROVIDER_RUN_JS_APP_SNP_IMAGE=${AZCLI_CCF_PROVIDER_RUN_JS_APP_SNP_IMAGE}
      - CCF_PROVIDER_RECOVERY_AGENT_IMAGE=${AZCLI_CCF_PROVIDER_RECOVERY_AGENT_IMAGE}
      - CCF_PROVIDER_RECOVERY_SERVICE_IMAGE=${AZCLI_CCF_PROVIDER_RECOVERY_SERVICE_IMAGE}
      - CCF_PROVIDER_PROXY_IMAGE=${AZCLI_CCF_PROVIDER_PROXY_IMAGE}
      - CCF_PROVIDER_ATTESTATION_IMAGE=${AZCLI_CCF_PROVIDER_ATTESTATION_IMAGE}
      - CCF_PROVIDER_SKR_IMAGE=${AZCLI_CCF_PROVIDER_SKR_IMAGE}
      - CCF_PROVIDER_NETWORK_SECURITY_POLICY_DOCUMENT_URL=${AZCLI_CCF_PROVIDER_NETWORK_SECURITY_POLICY_DOCUMENT_URL}
      - CCF_PROVIDER_RECOVERY_SERVICE_SECURITY_POLICY_DOCUMENT_URL=${AZCLI_CCF_PROVIDER_RECOVERY_SERVICE_SECURITY_POLICY_DOCUMENT_URL}
      - CCF_PROVIDER_CONTAINER_REGISTRY_URL=${AZCLI_CCF_PROVIDER_CONTAINER_REGISTRY_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
