services:
  client:
    image: mcr.microsoft.com/azurecleanroom/ccf/ccf-provider-client:5.0.0
    ports:
      - "0:8080"
    environment:
      - IDENTITY_ENDPOINT=${CREDENTIAL_PROXY_ENDPOINT}
      - IMDS_ENDPOINT="dummy_required_value"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
